site_name: <img src="" />
docs_dir: docs
site_dir: build/doc/
repo_url: https://github.com/PhpTyping/Types.git
use_directory_urls: false

theme:
    name: readthedocs
    nav_style: dark

nav:
    - Home: 'index.md'
    - Types:
          - Collection: 'types/collection.md'
          - DateTime: 'types/date-time.md'
          - Enum: 'types/enum.md'
          - BooleanObject: 'types/bool-object.md'
          - FloatObject: 'types/float-object.md'
          - IntObject: 'types/int-object.md'
          - StringObject: 'types/string-object.md'
    - Contributing:
          - Guidelines: 'contributing/guidelines.md'

extra_css:
    - css/blockquotes.css
    - css/tables.css
    - css/links.css

markdown_extensions:
    - toc:
          permalink: true
    - sane_lists
    - admonition
